BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SITES" (
	"CatID"	INTEGER NOT NULL,
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SiteName"	TEXT NOT NULL UNIQUE,
	"Password"	TEXT NOT NULL,
	FOREIGN KEY("CatID") REFERENCES "Categories"("ID")
);
CREATE TABLE IF NOT EXISTS "Categories" (
	"ID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"CatName"	TEXT NOT NULL UNIQUE
);
COMMIT;
